[path_comment]
enabled = true

[path_comment.formats]
".css" = "/* $path$file */"
".html" = "<!-- $path$file -->"
".js" = "/* $path$file */"
".mjs" = "/* $path$file */"
".ts" = "/* $path$file */"
".tsx" = "/* $path$file */"

[path_comment.exclude]
dirs = [".tanstack", ".wrangler", "dist", "node_modules"]
patterns = ["worker-configuration.d.ts", "routeTree.gen.ts"]
