// Drizzle schema. Tables generated by Better Auth's CLI live in
// auth-schema.ts (re-exported below); add app-specific tables in this
// file directly. Re-run `bunx @better-auth/cli generate` whenever the
// auth plugin set changes, then `just database-generate` to produce a
// migration.
export * from './auth-schema';
