/* scripts/gen-noise.ts */

import { deflateSync } from 'node:zlib'
import { writeFileSync } from 'node:fs'

// -- minimal PNG encoder --
function makePng(width: number, height: number, alpha: number): string {
	// deterministic LCG PRNG
	let seed = 42
	function nextBit(): number {
		seed = (seed * 1664525 + 1013904223) & 0xffffffff
		return (seed >>> 16) & 1
	}

	// build raw RGBA scanlines with filter byte 0 per row
	const raw = Buffer.alloc((1 + width * 4) * height)
	for (let y = 0; y < height; y++) {
		const offset = y * (1 + width * 4)
		raw[offset] = 0 // filter: none
		for (let x = 0; x < width; x++) {
			const px = offset + 1 + x * 4
			const v = nextBit() * 255
			raw[px] = v
			raw[px + 1] = v
			raw[px + 2] = v
			raw[px + 3] = alpha
		}
	}

	const compressed = deflateSync(raw)

	// helpers
	const signature = Buffer.from([137, 80, 78, 71, 13, 10, 26, 10])

	function chunk(type: string, data: Buffer): Buffer {
		const typeBytes = Buffer.from(type, 'ascii')
		const len = Buffer.alloc(4)
		len.writeUInt32BE(data.length)
		const payload = Buffer.concat([typeBytes, data])
		const crc = crc32(payload)
		const crcBuf = Buffer.alloc(4)
		crcBuf.writeUInt32BE(crc >>> 0)
		return Buffer.concat([len, payload, crcBuf])
	}

	// CRC-32
	const crcTable: number[] = []
	for (let n = 0; n < 256; n++) {
		let c = n
		for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1
		crcTable[n] = c
	}
	function crc32(buf: Buffer): number {
		let crc = 0xffffffff
		for (let i = 0; i < buf.length; i++) crc = crcTable[(crc ^ buf[i]) & 0xff] ^ (crc >>> 8)
		return (crc ^ 0xffffffff) >>> 0
	}

	// IHDR: width, height, bit depth 8, color type 6 (RGBA)
	const ihdrData = Buffer.alloc(13)
	ihdrData.writeUInt32BE(width, 0)
	ihdrData.writeUInt32BE(height, 4)
	ihdrData[8] = 8 // bit depth
	ihdrData[9] = 6 // color type RGBA
	ihdrData[10] = 0 // compression
	ihdrData[11] = 0 // filter
	ihdrData[12] = 0 // interlace

	const ihdr = chunk('IHDR', ihdrData)
	const idat = chunk('IDAT', compressed)
	const iend = chunk('IEND', Buffer.alloc(0))

	return Buffer.concat([signature, ihdr, idat, iend]).toString('base64')
}

// -- config --
const SIZE = 100
const LIGHT_ALPHA = 9
const DARK_ALPHA = 3

const lightB64 = makePng(SIZE, SIZE, LIGHT_ALPHA)
const darkB64 = makePng(SIZE, SIZE, DARK_ALPHA)

const css = `/* src/styles/noise.css */
/* generated by scripts/gen-noise.ts — do not edit by hand */
/* regenerate: bun run scripts/gen-noise.ts */

body {
	background-image: url("data:image/png;base64,${lightB64}");
	background-repeat: repeat;
}

.dark body {
	background-image: url("data:image/png;base64,${darkB64}");
}
`

writeFileSync('src/styles/noise.css', css)
console.log(
	`noise.css written — light alpha=${LIGHT_ALPHA}, dark alpha=${DARK_ALPHA}, tile=${SIZE}px`,
)
console.log(`  light base64: ${lightB64.length} chars`)
console.log(`  dark  base64: ${darkB64.length} chars`)