/* scripts/gen-world-map.ts */

/*
 * Rasterizes Natural Earth 110m land to a packed-bit grid and emits a
 * ready-to-import .ts data module. Run once and commit the output; this
 * is not part of the regular build pipeline.
 *
 * Usage: bun run scripts/gen-world-map.ts
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { geoContains } from 'd3-geo'
import { feature } from 'topojson-client'

const WIDTH = 360
const HEIGHT = 180
const INPUT = resolve('node_modules/world-atlas/land-110m.json')
const OUTPUT = resolve('src/components/footer-world-map-data.ts')

interface TopoLike {
  objects: { land: unknown }
}

function main() {
  const topology = JSON.parse(readFileSync(INPUT, 'utf-8')) as TopoLike
  // d3/topojson types are loose here; the runtime shape is a FeatureCollection
  // or Feature containing land MultiPolygon geometry, which geoContains accepts.
  const land = feature(
    topology as Parameters<typeof feature>[0],
    (topology.objects as { land: Parameters<typeof feature>[1] }).land,
  )

  const totalBits = WIDTH * HEIGHT
  const bytes = new Uint8Array(Math.ceil(totalBits / 8))

  for (let y = 0; y < HEIGHT; y++) {
    const lat = 90 - (y + 0.5) * (180 / HEIGHT)
    for (let x = 0; x < WIDTH; x++) {
      const lon = -180 + (x + 0.5) * (360 / WIDTH)
      // geoContains expects GeoJSON Feature/Geometry; cast through unknown to
      // satisfy the loose topojson typing.
      if (geoContains(land as never, [lon, lat])) {
        const i = y * WIDTH + x
        bytes[i >> 3]! |= 1 << (i & 7)
      }
    }
    if (y % 30 === 0) console.log(`  row ${y}/${HEIGHT}`)
  }

  const base64 = Buffer.from(bytes).toString('base64')

  const ts = `/* src/components/footer-world-map-data.ts */
/* Generated by scripts/gen-world-map.ts — do not edit by hand.
 * Source: Natural Earth 110m land via world-atlas.
 */

export const WORLD_MAP_WIDTH = ${WIDTH}
export const WORLD_MAP_HEIGHT = ${HEIGHT}

const BASE64 =
  '${base64}'

const BITS = /* @__PURE__ */ (() => {
  const binary = atob(BASE64)
  const arr = new Uint8Array(binary.length)
  for (let i = 0; i < binary.length; i++) arr[i] = binary.charCodeAt(i)
  return arr
})()

function readBit(x: number, y: number): number {
  const i = y * WORLD_MAP_WIDTH + x
  return ((BITS[i >> 3] ?? 0) >> (i & 7)) & 1
}

/** Bilinear sample of land density at a geographic point.
 * lon in [-180, 180] (wraps naturally outside), lat in [-90, 90].
 * Returns 0 (water) to 1 (land) with smooth transitions across neighbors.
 * -0.5 offsets align the query to each cell's center, since cell (x,y)
 * represents the center point lon=-180+(x+0.5), lat=90-(y+0.5). */
export function sampleLand(lon: number, lat: number): number {
  const normLon = (((lon + 180) % 360) + 360) % 360
  const u = (normLon / 360) * WORLD_MAP_WIDTH - 0.5
  const v = ((90 - lat) / 180) * WORLD_MAP_HEIGHT - 0.5
  const ux = Math.floor(u)
  const vy = Math.floor(v)
  const fx = u - ux
  const fy = v - vy
  const x0 = ((ux % WORLD_MAP_WIDTH) + WORLD_MAP_WIDTH) % WORLD_MAP_WIDTH
  const x1 = (x0 + 1) % WORLD_MAP_WIDTH
  const y0 = Math.max(0, Math.min(WORLD_MAP_HEIGHT - 1, vy))
  const y1 = Math.max(0, Math.min(WORLD_MAP_HEIGHT - 1, vy + 1))
  const a = readBit(x0, y0)
  const b = readBit(x1, y0)
  const c = readBit(x0, y1)
  const d = readBit(x1, y1)
  return (a * (1 - fx) + b * fx) * (1 - fy) + (c * (1 - fx) + d * fx) * fy
}
`

  mkdirSync(dirname(OUTPUT), { recursive: true })
  writeFileSync(OUTPUT, ts)
  console.log(
    `wrote ${OUTPUT}: ${bytes.length} bytes raw, ${base64.length} chars base64`,
  )
}

main()
