/* scripts/generate-noise.ts */

/* scripts/generate-noise.ts
 *
 * Generates noise textures as a single CSS file with inlined base64 PNGs.
 * Light and dark modes use separate presets for opacity.
 *
 * Usage:  bun run scripts/generate-noise.ts
 * Output: src/styles/noise.css
 */

import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { deflateSync } from 'node:zlib'

// ── Presets ─────────────────────────────────────────────────────
// Adjust these and re-run the script to regenerate.

const SIZE = 150
const LIGHT_OPACITY = 0.05
const DARK_OPACITY = 0.025
const OUTPUT = resolve(import.meta.dirname!, '..', 'src/styles/noise.css')

// ── PNG generation (grayscale noise, RGBA) ──────────────────────

function generateNoisePixels(size: number, opacity: number): Uint8Array {
  const rowLen = size * 4
  const raw = new Uint8Array((1 + rowLen) * size)
  const alpha = Math.floor(opacity * 255)

  for (let y = 0; y < size; y++) {
    const rowOffset = y * (1 + rowLen)
    raw[rowOffset] = 0 // PNG filter: None
    for (let x = 0; x < size; x++) {
      const px = rowOffset + 1 + x * 4
      const v = Math.floor(Math.random() * 256)
      raw[px] = v // R
      raw[px + 1] = v // G
      raw[px + 2] = v // B
      raw[px + 3] = alpha // A
    }
  }
  return raw
}

function crc32(buf: Uint8Array): number {
  let crc = 0xffffffff
  for (const byte of buf) {
    crc ^= byte
    for (let j = 0; j < 8; j++) {
      crc = (crc >>> 1) ^ (crc & 1 ? 0xedb88320 : 0)
    }
  }
  return (crc ^ 0xffffffff) >>> 0
}

function pngChunk(type: string, data: Uint8Array): Uint8Array {
  const typeBytes = new TextEncoder().encode(type)
  const len = new Uint8Array(4)
  new DataView(len.buffer).setUint32(0, data.length)

  const crcInput = new Uint8Array(typeBytes.length + data.length)
  crcInput.set(typeBytes)
  crcInput.set(data, typeBytes.length)
  const crc = new Uint8Array(4)
  new DataView(crc.buffer).setUint32(0, crc32(crcInput))

  const chunk = new Uint8Array(4 + typeBytes.length + data.length + 4)
  chunk.set(len)
  chunk.set(typeBytes, 4)
  chunk.set(data, 8)
  chunk.set(crc, 8 + data.length)
  return chunk
}

function buildPng(size: number, opacity: number): Uint8Array {
  const signature = new Uint8Array([137, 80, 78, 71, 13, 10, 26, 10])

  const ihdrData = new Uint8Array(13)
  const ihdrView = new DataView(ihdrData.buffer)
  ihdrView.setUint32(0, size)
  ihdrView.setUint32(4, size)
  ihdrData[8] = 8 // bit depth
  ihdrData[9] = 6 // color type (RGBA)
  const ihdr = pngChunk('IHDR', ihdrData)

  const raw = generateNoisePixels(size, opacity)
  const compressed = deflateSync(raw)
  const idat = pngChunk('IDAT', compressed)

  const iend = pngChunk('IEND', new Uint8Array(0))

  const png = new Uint8Array(
    signature.length + ihdr.length + idat.length + iend.length,
  )
  let offset = 0
  for (const part of [signature, ihdr, idat, iend]) {
    png.set(part, offset)
    offset += part.length
  }
  return png
}

function toDataUri(png: Uint8Array): string {
  return `data:image/png;base64,${Buffer.from(png).toString('base64')}`
}

// ── Generate and write CSS ──────────────────────────────────────

const lightUri = toDataUri(buildPng(SIZE, LIGHT_OPACITY))
const darkUri = toDataUri(buildPng(SIZE, DARK_OPACITY))

const css = `/* Generated by scripts/generate-noise.ts — do not edit manually */
/* Size: ${SIZE}x${SIZE}, Light opacity: ${LIGHT_OPACITY}, Dark opacity: ${DARK_OPACITY} */

.noise-bg::before {
  content: '';
  position: absolute;
  inset: 0;
  z-index: 1;
  pointer-events: none;
  background-image: url("${lightUri}");
  background-repeat: repeat;
}

.dark .noise-bg::before {
  background-image: url("${darkUri}");
}
`

writeFileSync(OUTPUT, css)
console.log(
  `Noise CSS written to ${OUTPUT} (${SIZE}x${SIZE}, light=${LIGHT_OPACITY}, dark=${DARK_OPACITY})`,
)
