/* src/components/post/post-renderer.tsx */

import type { ComponentEntry } from '~/lib/compiler/index'
import { ComponentResolver } from './component-resolver'

interface PostRendererProps {
  html: string
  components: ComponentEntry[]
}

// HTML is generated by our own compiler pipeline from trusted markdown
// content stored in D1, not from user-submitted input.
export function PostRenderer({ html, components }: PostRendererProps) {
  if (components.length === 0) {
    return <div dangerouslySetInnerHTML={{ __html: html }} />
  }

  // Split HTML by component placeholders
  const parts = html.split(/(<!--component:\d+-->)/)

  return (
    <div>
      {parts.map((part, i) => {
        const match = part.match(/<!--component:(\d+)-->/)
        if (match) {
          const index = Number(match[1])
          const entry = components[index]
          if (!entry) return null
          return <ComponentResolver key={`c${index}`} entry={entry} />
        }
        if (part) {
          // Parts are derived from a stable split — index keys are safe here
          // oxlint-disable-next-line react/no-array-index-key
          return <div key={i} dangerouslySetInnerHTML={{ __html: part }} />
        }
        return null
      })}
    </div>
  )
}
