/* src/components/post/post-renderer.tsx */

import { useCallback } from 'react'
import type { ComponentEntry } from '~/lib/compiler/index'
import { ComponentResolver } from './component-resolver'

interface PostRendererProps {
  html: string
  components: ComponentEntry[]
}

// HTML is generated by our own compiler pipeline from trusted markdown
// content stored in D1, not from user-submitted input.
export function PostRenderer({ html, components }: PostRendererProps) {
  const handleHeadingLinkClick = useCallback(
    (e: React.MouseEvent<HTMLDivElement>) => {
      const target = e.target
      if (!(target instanceof Element)) return

      const link = target.closest('a[data-heading-link="true"]')
      if (!(link instanceof HTMLAnchorElement)) return

      e.preventDefault()

      const id = link.dataset.headingId
      if (!id) return

      const { pathname, search, hash } = window.location
      const nextHash = `#${id}`
      if (hash === nextHash) return
      window.history.replaceState(null, '', `${pathname}${search}${nextHash}`)
    },
    [],
  )

  if (components.length === 0) {
    return (
      <div
        onClickCapture={handleHeadingLinkClick}
        dangerouslySetInnerHTML={{ __html: html }}
      />
    )
  }

  // Split HTML by component placeholders
  const parts = html.split(/(<!--component:\d+-->)/)

  return (
    <div onClickCapture={handleHeadingLinkClick}>
      {parts.map((part, i) => {
        const match = part.match(/<!--component:(\d+)-->/)
        if (match) {
          const index = Number(match[1])
          const entry = components[index]
          if (!entry) return null
          return <ComponentResolver key={`c${index}`} entry={entry} />
        }
        if (part) {
          // Parts are derived from a stable split — index keys are safe here
          // oxlint-disable-next-line react/no-array-index-key
          return <div key={i} dangerouslySetInnerHTML={{ __html: part }} />
        }
        return null
      })}
    </div>
  )
}
