/* src/components/post/renderer.tsx */

/* eslint-disable better-tailwindcss/no-unknown-classes */

import { useCallback, useEffect, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Hash } from 'lucide-react'
import { motion, AnimatePresence } from 'motion/react'
import type { ComponentEntry } from '~/lib/compiler/index'
import { ComponentResolver } from './component-resolver'

function HeadingLinkIcon({ parent }: { parent: HTMLElement }) {
  const [visible, setVisible] = useState(false)

  useEffect(() => {
    const show = () => setVisible(true)
    const hide = () => setVisible(false)
    parent.addEventListener('mouseenter', show)
    parent.addEventListener('mouseleave', hide)
    return () => {
      parent.removeEventListener('mouseenter', show)
      parent.removeEventListener('mouseleave', hide)
    }
  }, [parent])

  return (
    <AnimatePresence>
      {visible && (
        <motion.span
          className="heading-link-icon"
          initial={{ opacity: 0, scale: 0.6 }}
          animate={{ opacity: 1, scale: 1 }}
          exit={{ opacity: 0, scale: 0.6 }}
          transition={{ duration: 0.18, ease: [0.22, 1, 0.36, 1] }}
        >
          <Hash size={14} strokeWidth={2} aria-hidden="true" />
        </motion.span>
      )}
    </AnimatePresence>
  )
}

interface PostRendererProps {
  html: string
  components: ComponentEntry[]
}

// HTML is generated by our own compiler pipeline from trusted markdown
// content stored in D1, not from user-submitted input.
export function PostRenderer({ html, components }: PostRendererProps) {
  const containerRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    const container = containerRef.current
    if (!container) return

    const links = container.querySelectorAll<HTMLAnchorElement>(
      'a[data-heading-link="true"]',
    )
    const roots: ReturnType<typeof createRoot>[] = []

    for (const link of links) {
      if (link.children.length > 0) continue
      const heading = link.parentElement
      if (!heading) continue
      const root = createRoot(link)
      root.render(<HeadingLinkIcon parent={heading} />)
      roots.push(root)
    }

    return () => {
      for (const root of roots) root.unmount()
    }
  }, [html])

  const handleHeadingLinkClick = useCallback(
    (e: React.MouseEvent<HTMLDivElement>) => {
      const target = e.target
      if (!(target instanceof Element)) return

      const link = target.closest('a[data-heading-link="true"]')
      if (!(link instanceof HTMLAnchorElement)) return

      e.preventDefault()

      const id = link.dataset.headingId
      if (!id) return

      const { pathname, search, hash } = window.location
      const nextHash = `#${id}`
      if (hash === nextHash) return
      window.history.replaceState(null, '', `${pathname}${search}${nextHash}`)
    },
    [],
  )

  if (components.length === 0) {
    return (
      <div
        ref={containerRef}
        onClickCapture={handleHeadingLinkClick}
        dangerouslySetInnerHTML={{ __html: html }}
      />
    )
  }

  // Split HTML by component placeholders
  const parts = html.split(/(<!--component:\d+-->)/)

  return (
    <div ref={containerRef} onClickCapture={handleHeadingLinkClick}>
      {parts.map((part, i) => {
        const match = part.match(/<!--component:(\d+)-->/)
        if (match) {
          const index = Number(match[1])
          const entry = components[index]
          if (!entry) return null
          return <ComponentResolver key={`c${index}`} entry={entry} />
        }
        if (part) {
          // Parts are derived from a stable split — index keys are safe here
          // oxlint-disable-next-line react/no-array-index-key
          return <div key={i} dangerouslySetInnerHTML={{ __html: part }} />
        }
        return null
      })}
    </div>
  )
}
