/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as FeedDotxmlRouteImport } from './routes/feed[.]xml'
import { Route as AtRouteRouteImport } from './routes/@/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapIndexRouteImport } from './routes/sitemap/index'
import { Route as RssIndexRouteImport } from './routes/rss/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as FeedIndexRouteImport } from './routes/feed/index'
import { Route as AtDashboardRouteRouteImport } from './routes/@/_dashboard/route'
import { Route as LoginVerifyIndexRouteImport } from './routes/login/verify/index'
import { Route as AtDashboardIndexRouteImport } from './routes/@/_dashboard/index'
import { Route as ApiObjectSplatRouteImport } from './routes/api/object/$'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PostsCategorySlugIndexRouteImport } from './routes/posts/$category/$slug/index'
import { Route as AtEditorCidIndexRouteImport } from './routes/@/editor/$cid/index'
import { Route as AtDashboardContentsIndexRouteImport } from './routes/@/_dashboard/contents/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedDotxmlRoute = FeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AtRouteRoute = AtRouteRouteImport.update({
  id: '/@',
  path: '/@',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapIndexRoute = SitemapIndexRouteImport.update({
  id: '/sitemap/',
  path: '/sitemap/',
  getParentRoute: () => rootRouteImport,
} as any)
const RssIndexRoute = RssIndexRouteImport.update({
  id: '/rss/',
  path: '/rss/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedIndexRoute = FeedIndexRouteImport.update({
  id: '/feed/',
  path: '/feed/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtDashboardRouteRoute = AtDashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => AtRouteRoute,
} as any)
const LoginVerifyIndexRoute = LoginVerifyIndexRouteImport.update({
  id: '/login/verify/',
  path: '/login/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtDashboardIndexRoute = AtDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AtDashboardRouteRoute,
} as any)
const ApiObjectSplatRoute = ApiObjectSplatRouteImport.update({
  id: '/api/object/$',
  path: '/api/object/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsCategorySlugIndexRoute = PostsCategorySlugIndexRouteImport.update({
  id: '/posts/$category/$slug/',
  path: '/posts/$category/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtEditorCidIndexRoute = AtEditorCidIndexRouteImport.update({
  id: '/editor/$cid/',
  path: '/editor/$cid/',
  getParentRoute: () => AtRouteRoute,
} as any)
const AtDashboardContentsIndexRoute =
  AtDashboardContentsIndexRouteImport.update({
    id: '/contents/',
    path: '/contents/',
    getParentRoute: () => AtDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/@': typeof AtDashboardRouteRouteWithChildren
  '/feed.xml': typeof FeedDotxmlRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/feed/': typeof FeedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/rss/': typeof RssIndexRoute
  '/sitemap/': typeof SitemapIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/object/$': typeof ApiObjectSplatRoute
  '/@/': typeof AtDashboardIndexRoute
  '/login/verify/': typeof LoginVerifyIndexRoute
  '/@/contents/': typeof AtDashboardContentsIndexRoute
  '/@/editor/$cid/': typeof AtEditorCidIndexRoute
  '/posts/$category/$slug/': typeof PostsCategorySlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/@': typeof AtDashboardIndexRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/feed': typeof FeedIndexRoute
  '/login': typeof LoginIndexRoute
  '/posts': typeof PostsIndexRoute
  '/rss': typeof RssIndexRoute
  '/sitemap': typeof SitemapIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/object/$': typeof ApiObjectSplatRoute
  '/login/verify': typeof LoginVerifyIndexRoute
  '/@/contents': typeof AtDashboardContentsIndexRoute
  '/@/editor/$cid': typeof AtEditorCidIndexRoute
  '/posts/$category/$slug': typeof PostsCategorySlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/@': typeof AtRouteRouteWithChildren
  '/feed.xml': typeof FeedDotxmlRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/@/_dashboard': typeof AtDashboardRouteRouteWithChildren
  '/feed/': typeof FeedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/rss/': typeof RssIndexRoute
  '/sitemap/': typeof SitemapIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/object/$': typeof ApiObjectSplatRoute
  '/@/_dashboard/': typeof AtDashboardIndexRoute
  '/login/verify/': typeof LoginVerifyIndexRoute
  '/@/_dashboard/contents/': typeof AtDashboardContentsIndexRoute
  '/@/editor/$cid/': typeof AtEditorCidIndexRoute
  '/posts/$category/$slug/': typeof PostsCategorySlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/@'
    | '/feed.xml'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/feed/'
    | '/login/'
    | '/posts/'
    | '/rss/'
    | '/sitemap/'
    | '/api/auth/$'
    | '/api/auth/me'
    | '/api/object/$'
    | '/@/'
    | '/login/verify/'
    | '/@/contents/'
    | '/@/editor/$cid/'
    | '/posts/$category/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/@'
    | '/feed.xml'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/feed'
    | '/login'
    | '/posts'
    | '/rss'
    | '/sitemap'
    | '/api/auth/$'
    | '/api/auth/me'
    | '/api/object/$'
    | '/login/verify'
    | '/@/contents'
    | '/@/editor/$cid'
    | '/posts/$category/$slug'
  id:
    | '__root__'
    | '/'
    | '/@'
    | '/feed.xml'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/@/_dashboard'
    | '/feed/'
    | '/login/'
    | '/posts/'
    | '/rss/'
    | '/sitemap/'
    | '/api/auth/$'
    | '/api/auth/me'
    | '/api/object/$'
    | '/@/_dashboard/'
    | '/login/verify/'
    | '/@/_dashboard/contents/'
    | '/@/editor/$cid/'
    | '/posts/$category/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtRouteRoute: typeof AtRouteRouteWithChildren
  FeedDotxmlRoute: typeof FeedDotxmlRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  FeedIndexRoute: typeof FeedIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  PostsIndexRoute: typeof PostsIndexRoute
  RssIndexRoute: typeof RssIndexRoute
  SitemapIndexRoute: typeof SitemapIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiObjectSplatRoute: typeof ApiObjectSplatRoute
  LoginVerifyIndexRoute: typeof LoginVerifyIndexRoute
  PostsCategorySlugIndexRoute: typeof PostsCategorySlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed.xml': {
      id: '/feed.xml'
      path: '/feed.xml'
      fullPath: '/feed.xml'
      preLoaderRoute: typeof FeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@': {
      id: '/@'
      path: '/@'
      fullPath: '/@'
      preLoaderRoute: typeof AtRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/': {
      id: '/sitemap/'
      path: '/sitemap'
      fullPath: '/sitemap/'
      preLoaderRoute: typeof SitemapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss/': {
      id: '/rss/'
      path: '/rss'
      fullPath: '/rss/'
      preLoaderRoute: typeof RssIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/': {
      id: '/feed/'
      path: '/feed'
      fullPath: '/feed/'
      preLoaderRoute: typeof FeedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@/_dashboard': {
      id: '/@/_dashboard'
      path: ''
      fullPath: '/@'
      preLoaderRoute: typeof AtDashboardRouteRouteImport
      parentRoute: typeof AtRouteRoute
    }
    '/login/verify/': {
      id: '/login/verify/'
      path: '/login/verify'
      fullPath: '/login/verify/'
      preLoaderRoute: typeof LoginVerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@/_dashboard/': {
      id: '/@/_dashboard/'
      path: '/'
      fullPath: '/@/'
      preLoaderRoute: typeof AtDashboardIndexRouteImport
      parentRoute: typeof AtDashboardRouteRoute
    }
    '/api/object/$': {
      id: '/api/object/$'
      path: '/api/object/$'
      fullPath: '/api/object/$'
      preLoaderRoute: typeof ApiObjectSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$category/$slug/': {
      id: '/posts/$category/$slug/'
      path: '/posts/$category/$slug'
      fullPath: '/posts/$category/$slug/'
      preLoaderRoute: typeof PostsCategorySlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@/editor/$cid/': {
      id: '/@/editor/$cid/'
      path: '/editor/$cid'
      fullPath: '/@/editor/$cid/'
      preLoaderRoute: typeof AtEditorCidIndexRouteImport
      parentRoute: typeof AtRouteRoute
    }
    '/@/_dashboard/contents/': {
      id: '/@/_dashboard/contents/'
      path: '/contents'
      fullPath: '/@/contents/'
      preLoaderRoute: typeof AtDashboardContentsIndexRouteImport
      parentRoute: typeof AtDashboardRouteRoute
    }
  }
}

interface AtDashboardRouteRouteChildren {
  AtDashboardIndexRoute: typeof AtDashboardIndexRoute
  AtDashboardContentsIndexRoute: typeof AtDashboardContentsIndexRoute
}

const AtDashboardRouteRouteChildren: AtDashboardRouteRouteChildren = {
  AtDashboardIndexRoute: AtDashboardIndexRoute,
  AtDashboardContentsIndexRoute: AtDashboardContentsIndexRoute,
}

const AtDashboardRouteRouteWithChildren =
  AtDashboardRouteRoute._addFileChildren(AtDashboardRouteRouteChildren)

interface AtRouteRouteChildren {
  AtDashboardRouteRoute: typeof AtDashboardRouteRouteWithChildren
  AtEditorCidIndexRoute: typeof AtEditorCidIndexRoute
}

const AtRouteRouteChildren: AtRouteRouteChildren = {
  AtDashboardRouteRoute: AtDashboardRouteRouteWithChildren,
  AtEditorCidIndexRoute: AtEditorCidIndexRoute,
}

const AtRouteRouteWithChildren =
  AtRouteRoute._addFileChildren(AtRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtRouteRoute: AtRouteRouteWithChildren,
  FeedDotxmlRoute: FeedDotxmlRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  FeedIndexRoute: FeedIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  PostsIndexRoute: PostsIndexRoute,
  RssIndexRoute: RssIndexRoute,
  SitemapIndexRoute: SitemapIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiObjectSplatRoute: ApiObjectSplatRoute,
  LoginVerifyIndexRoute: LoginVerifyIndexRoute,
  PostsCategorySlugIndexRoute: PostsCategorySlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
